### ISSUE TITLE
1.4.10 tagged version failed on wpackagist

### ISSUE THREAD

**Issue by kl3sk** [JulioPotier/secupress#68] opened 2019-09-23 13:39 UTC
Hello,

Please, update you `package.json` or add a tag for v1.4.10
this version failed on download due too a non existing package.

`https://downloads.wordpress.org/plugin/secupress.1.4.10.zip`

Which this tag is referenced in your package.json but no such branch exists.
And this tag is read by `wpagagist.org` and certainly by `packagist.org` too

**Comment by lhall-amphibee** [comment] 2019-10-25 07:41
One month later, the problem is still there. Is this plugin still alive ?

**Comment by kl3sk** [comment] 2019-10-25 08:16
@lhall-adexos if you are in the same situation as me (let using wpackagist).
My workaround was to use `dev-trunk` inside de `package.json`

**Comment by JulioPotier** [comment] 2019-10-25 08:27
yes still but I don't release a version "just" for that, sorry. An update is under dev and will be released, thank you for your patience and sorry for the inconvenience!

**Comment by kl3sk** [comment] 2019-10-25 08:41
Why ?
There is already a v1.4.10 !
All `package.json` fails because of this existing tag !

**Comment by JulioPotier** [comment] 2019-10-25 08:49
Maybe I'm not getting it, I thought the problem was an missing version number update. What do you expect, I'll try to do it asap.

**Comment by kl3sk** [comment] 2019-10-25 09:05
As I said on `wpackagist` the 1.4.10 pops.

![image](https://user-images.githubusercontent.com/2953145/67558414-3d85d400-f717-11e9-8df9-82a23ed2c407.png)

Because of an empty package I have to use the `dev-trunck` that is (I think) not a stable version. And In fact I don't want to rollback to an older version.

Is it clearer ?

**Comment by JulioPotier** [comment] 2019-10-25 09:06
Yes thank you and for info, trunk is always equal to the last stable tag for me. I don't push in trunk during dev.

**Comment by kl3sk** [comment] 2019-10-25 09:11
Ok, this is not obvious that a `dev` branch is stable :blush:

**Comment by JulioPotier** [comment] 2019-10-25 09:14
We're talking about the "trunk" one on wp.org right? I don't have a trunk here.

**Comment by kl3sk** [comment] 2019-10-25 09:20
> trunk is always equal to the last stable tag for me

Yep, I don't know how they manage their branches/tags, this is strange I concede.
But as a user I read `dev`.

> I don't have a trunk here

:confused:

_Edit:_
I think their `dev-trunk` is your `dev-master`

**Comment by JulioPotier** [comment] 2019-10-25 09:23
link me the branch you're using, thank you

**Comment by kl3sk** [comment] 2019-10-25 09:24
I'am using composer `"wpackagist-plugin/secupress":"dev-trunk"`

https://github.com/outlandishideas/wpackagist/issues/300

**Comment by JulioPotier** [comment] 2019-10-25 09:43
omg got it. the content is missing from snv tags/1.4.10, this is clear now.
I'm uploading it right now, should be good in 15/20 min (yes SVN is crazy slow)

**Comment by lhall-amphibee** [comment] 2019-10-25 12:31
Website working again, thanks for the upload !

**Closed as completed** 2021-03-19 12:45 UTC
